import pickle
import streamlit as st
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler


# Initialize StandardScaler
with open(r"C:\Users\RAaM\OneDrive\Desktop\Monetory\scaler.pkl", 'rb') as file:
    ss = pickle.load(file)

# Load the model from file
with open(r"C:\Users\RAaM\OneDrive\Desktop\Monetory\model.pkl", 'rb') as file:
    model = pickle.load(file)

st.sidebar.title('Navigation')
selection = st.sidebar.radio('Go to', ['Home', 'Predict'])
if selection == 'Home':
    st.title(' Content Monetization Modeler')
    st.image(r"C:\Users\RAaM\OneDrive\Desktop\Monetory\CMMImage.webp")
    st.write("""The Content Monetization Modeler is a machine learning project designed to predict revenue based on video performance metrics and audience engagement. 
             The project analyzes factors such as views, likes, comments, watch time, video length, subscribers, category, device type, country, and publishing
             date to estimate the potential ad revenue generated by a video.""")
    
    st.write("""This project demonstrates a complete end-to-end machine learning workflow,
              from data preprocessing and exploratory analysis to model development, evaluation, and deployment for practical business decision-making.""")

    st.write("Explore the dataset, [click here](https://drive.google.com/drive/folders/1ybhXuva11b6zm20j35vXC33E75FS0sHN?usp=sharing).")
    
 
elif selection == 'Predict':
    st.title('Predict')

# Create two columns
    col1, col2 = st.columns(2)			 																				

    with col1:
        views = st.number_input('Views',min_value=1)
        likes= st.number_input('Likes',min_value=0)
        comments= st.number_input('Comments',min_value=0)
        watch_time	= st.number_input('Watch time',min_value=1.0)
        video_length= st.number_input('Video length',min_value=1.0)

    with col2:
        subscribers = st.number_input('Subscribers',min_value=0)
        # Date Input
        publish_date = st.date_input("Publish Date")
        # Categorical Inputs
        category = st.selectbox("Category", ["Entertainment", "Gaming", "Lifestyle", "Music", "Tech"])
        device = st.selectbox("Device",  ["Mobile", "TV", "Tablet"])
        country = st.selectbox("Country",["CA", "DE", "IN", "UK", "US"])

        year = publish_date.year
        month = publish_date.month
        day = publish_date.day
        day_name = publish_date.strftime("%A")
        engagement_rate = (likes + comments) / views
        like_ratio = likes / views
        watch_time_per_view = watch_time / views

        log_views = np.log1p(views)
        log_likes = np.log1p(likes)
        log_comments = np.log1p(comments)
        log_subscribers = np.log1p(subscribers)

    new_data = pd.DataFrame({
    'views': [views],
    'likes': [likes],
    'comments': [comments],
    'watch_time_minutes': [watch_time],
    'video_length_minutes': [video_length],
    'subscribers': [subscribers],

    'log_views': [log_views],
    'log_likes': [log_likes],
    'log_comments': [log_comments],
    'log_subscribers': [log_subscribers],

    'year': [year],
    'month': [month],
    'day': [day],

    'engagement_rate': [engagement_rate],
    'like_ratio': [like_ratio],
    'watch_time_per_view': [watch_time_per_view],

    # Category
    'category_Entertainment': [1 if category == "Entertainment" else 0],
    'category_Gaming': [1 if category == "Gaming" else 0],
    'category_Lifestyle': [1 if category == "Lifestyle" else 0],
    'category_Music': [1 if category == "Music" else 0],
    'category_Tech': [1 if category == "Tech" else 0],

    # Device
    'device_Mobile': [1 if device == "Mobile" else 0],
    'device_TV': [1 if device == "TV" else 0],
    'device_Tablet': [1 if device == "Tablet" else 0],

    # Country
    'country_CA': [1 if country == "CA" else 0],
    'country_DE': [1 if country == "DE" else 0],
    'country_IN': [1 if country == "IN" else 0],
    'country_UK': [1 if country == "UK" else 0],
    'country_US': [1 if country == "US" else 0],

    # Day of Week
    'day_of_week_Monday': [1 if day_name == "Monday" else 0],
    'day_of_week_Saturday': [1 if day_name == "Saturday" else 0],
    'day_of_week_Sunday': [1 if day_name == "Sunday" else 0],
    'day_of_week_Thursday': [1 if day_name == "Thursday" else 0],
    'day_of_week_Tuesday': [1 if day_name == "Tuesday" else 0],
    'day_of_week_Wednesday': [1 if day_name == "Wednesday" else 0],

    # Video Length Category
    'video_length_category_Medium': [1 if 10 <= video_length <= 30 else 0],
    'video_length_category_Short': [1 if video_length < 10 else 0]
})
    

    feature_columns = [
    'views', 'likes', 'comments', 'watch_time_minutes',
    'video_length_minutes', 'subscribers',
    'log_views', 'log_likes', 'log_comments',
    'log_subscribers',
    'year', 'month', 'day',
    'engagement_rate', 'like_ratio',
    'watch_time_per_view',
    'category_Entertainment',
    'category_Gaming',
    'category_Lifestyle',
    'category_Music',
    'category_Tech',
    'device_Mobile',
    'device_TV',
    'device_Tablet',
    'country_CA',
    'country_DE',
    'country_IN',
    'country_UK',
    'country_US',
    'day_of_week_Monday',
    'day_of_week_Saturday',
    'day_of_week_Sunday',
    'day_of_week_Thursday',
    'day_of_week_Tuesday',
    'day_of_week_Wednesday',
    'video_length_category_Medium',
    'video_length_category_Short'
]

if st.button("Predict Ad Revenue"):
    # Arrange columns in the same order as the training data
    new_data = new_data.reindex(columns=feature_columns, fill_value=0)

    # Scale the data
    new_data_scaled = ss.transform(new_data)

    # Predict
    prediction = model.predict(new_data_scaled)
    st.success(f"Predicted Ad Revenue: ${prediction[0]:,.2f}")

        



                    